-- /*
-- Navicat MySQL Data Transfer
--
-- Source Server         : location
-- Source Server Version : 80011
-- Source Host           : localhost:3306
-- Source Database       : test
--
-- Target Server Type    : MYSQL
-- Target Server Version : 80011
-- File Encoding         : 65001
--
-- Date: 2018-06-26 16:55:09
-- */
--
-- SET FOREIGN_KEY_CHECKS=0;
--
-- -- ----------------------------
-- -- Table structure for `user`
-- -- ----------------------------
-- DROP TABLE IF EXISTS `user`;
-- CREATE TABLE `user` (
--   `uid` int(11) NOT NULL AUTO_INCREMENT,
--   `username` varchar(255) DEFAULT NULL,
--   `password` varchar(255) DEFAULT NULL,
--   PRIMARY KEY (`uid`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
--
-- -- ----------------------------
-- -- Records of user
-- -- ----------------------------
-- INSERT INTO `user` VALUES ('1', 'admin', '123456');
